In [1]:
# Install requests if not already available
!pip install requests --quiet

# The --quiet flag suppresses the installation output
# so our notebook stays clean

import pandas as pd

# pandas: our core data manipulation library from Days 1 & 2

import numpy as np

# numpy: numerical operations library
# We use it for np.nan (Not a Number — the standard missing value in Python)

import requests

# requests: the standard Python library for making HTTP API calls
# NOT built-in — must be installed (done above)

import matplotlib.pyplot as plt

# matplotlib.pyplot: our charting library from Day 2

import warnings

warnings.filterwarnings('ignore')

print("All libraries imported successfully!")

print(f"pandas : {pd.__version__}")

print(f"requests: {requests.__version__}")

All libraries imported successfully!
pandas : 2.2.2
requests: 2.32.4

In [2]:
# ==========================================================
# PART 1: ETL on Messy Sales Data
# ==========================================================

# Activity 1 — Clean messy_sales_data.csv

# Upload messy_sales_data.csv to Colab Files panel,
# then run the cells below.

In [3]:
# ==========================================================
# CELL 2 — EXTRACT: Load raw messy sales data
# ==========================================================

raw_df = pd.read_csv('messy_sales_data.csv')

# We store the RAW data in 'raw_df'

# ETL best practice: NEVER modify raw data

# Always work on a copy so you can go back to the original

print(f"Raw data loaded: {raw_df.shape[0]} rows, {raw_df.shape[1]} columns")

print(f"Columns: {raw_df.columns.tolist()}")

print("\nFirst 5 rows:")

raw_df.head()

Raw data loaded: 30 rows, 9 columns
Columns: ['order_id', 'customer_name', 'product', 'category', 'quantity', 'unit_price', 'order_date', 'city', 'sales_rep']

First 5 rows:

,order_id,customer_name,product,category,quantity,unit_price,order_date,city,sales_rep
0,1001,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma
1,1002,Priya Nair,NaN,Electronics,1.0,15000,2024-01-07,Delhi,Sunita Rao
2,1003,AMIT VERMA,Keyboard,Accessories,3.0,1200,2024-01-08,Bangalore,Anil Sharma
3,1004,Sunita Patel,Monitor,Electronics,NaN,22000,2024-01-10,Chennai,Ravi Kumar
4,1005,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma

In [4]:
# ==========================================================
# CELL 3 — Diagnose ALL data quality problems before fixing
# ==========================================================

print("=" * 55)

print(" DATA QUALITY DIAGNOSIS REPORT ")

print("=" * 55)

# Check missing values

print("\nMissing Values:\n")

print(raw_df.isnull().sum())

# Check duplicate rows

print("\nDuplicate Rows:")

print(raw_df.duplicated().sum())

# Check data types

print("\nData Types:\n")

print(raw_df.dtypes)

# Unique category values

print("\nUnique Categories:\n")

print(raw_df['category'].unique())

=======================================================
 DATA QUALITY DIAGNOSIS REPORT
=======================================================

Missing Values:

order_id         0
customer_name    2
product          1
category         1
quantity         3
unit_price       0
order_date       0
city             0
sales_rep        0
dtype: int64

Duplicate Rows:
0

Data Types:

order_id           int64
customer_name     object
product           object
category          object
quantity         float64
unit_price         int64
order_date        object
city              object
sales_rep         object
dtype: object

Unique Categories:

['Electronics' 'Accessories' nan]

In [5]:
# ==========================================================
# CELL 4 — TRANSFORM: Create clean working copy
# ==========================================================

clean_df = raw_df.copy()

# We now work on clean_df
# raw_df remains untouched as backup

print("Working copy created successfully!")

Working copy created successfully!

In [7]:
print(clean_df.columns)

Index(['order_id', 'customer_name', 'product', 'category', 'quantity',
       'unit_price', 'order_date', 'city', 'sales_rep'],
      dtype='object')

In [8]:
print(clean_df.columns)

Index(['order_id', 'customer_name', 'product', 'category', 'quantity',
       'unit_price', 'order_date', 'city', 'sales_rep'],
      dtype='object')

In [9]:
print(clean_df.columns)

Index(['order_id', 'customer_name', 'product', 'category', 'quantity',
       'unit_price', 'order_date', 'city', 'sales_rep'],
      dtype='object')

In [11]:
# ==========================================================
# CELL 5 — Handle Missing Values
# ==========================================================

print("Missing values before cleaning:\n")

print(clean_df.isnull().sum())

# Fill missing quantity values with median

clean_df['quantity'].fillna(
    clean_df['quantity'].median(),
    inplace=True
)

# Fill missing category values with mode

clean_df['category'].fillna(
    clean_df['category'].mode()[0],
    inplace=True
)

# Fill missing product values with mode

clean_df['product'].fillna(
    clean_df['product'].mode()[0],
    inplace=True
)

print("\nMissing values after cleaning:\n")

print(clean_df.isnull().sum())

Missing values before cleaning:

order_id         0
customer_name    2
product          1
category         1
quantity         3
unit_price       0
order_date       0
city             0
sales_rep        0
dtype: int64

Missing values after cleaning:

order_id         0
customer_name    2
product          0
category         0
quantity         0
unit_price       0
order_date       0
city             0
sales_rep        0
dtype: int64

In [12]:
# ==========================================================
# CELL 6 — Remove Duplicate Rows
# ==========================================================

print("Rows before removing duplicates:")

print(clean_df.shape[0])

# Remove duplicate rows

clean_df.drop_duplicates(inplace=True)

print("\nRows after removing duplicates:")

print(clean_df.shape[0])

Rows before removing duplicates:
30

Rows after removing duplicates:
30

In [13]:
# ==========================================================
# CELL 7 — Standardize Category Names
# ==========================================================

print("Unique categories before cleaning:\n")

print(clean_df['category'].unique())

# Convert category names to uppercase

clean_df['category'] = clean_df['category'].str.upper()

print("\nUnique categories after cleaning:\n")

print(clean_df['category'].unique())

Unique categories before cleaning:

['Electronics' 'Accessories']

Unique categories after cleaning:

['ELECTRONICS' 'ACCESSORIES']

In [14]:
# ==========================================================
# CELL 8 — Final Clean Dataset Preview
# ==========================================================

print("Final cleaned dataset shape:")

print(clean_df.shape)

print("\nFirst 5 rows of cleaned data:\n")

clean_df.head()

Final cleaned dataset shape:
(30, 9)

First 5 rows of cleaned data:

,order_id,customer_name,product,category,quantity,unit_price,order_date,city,sales_rep
0,1001,Ramesh Kumar,Laptop,ELECTRONICS,2.0,45000,2024-01-05,Mumbai,Anil Sharma
1,1002,Priya Nair,Laptop,ELECTRONICS,1.0,15000,2024-01-07,Delhi,Sunita Rao
2,1003,AMIT VERMA,Keyboard,ACCESSORIES,3.0,1200,2024-01-08,Bangalore,Anil Sharma
3,1004,Sunita Patel,Monitor,ELECTRONICS,2.0,22000,2024-01-10,Chennai,Ravi Kumar
4,1005,Ramesh Kumar,Laptop,ELECTRONICS,2.0,45000,2024-01-05,Mumbai,Anil Sharma

In [15]:
# ==========================================================
# CELL 9 — Save Cleaned Dataset
# ==========================================================

clean_df.to_csv('cleaned_sales_data.csv', index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [16]:
# ==========================================================
# CELL 10 — Summary Report
# ==========================================================

print("=" * 55)

print(" FINAL ETL SUMMARY REPORT ")

print("=" * 55)

print(f"Total Rows : {clean_df.shape[0]}")

print(f"Total Columns : {clean_df.shape[1]}")

print("\nColumn Names:\n")

print(clean_df.columns.tolist())

print("\nData Types:\n")

print(clean_df.dtypes)

print("\nFirst 5 Rows of Cleaned Dataset:\n")

print(clean_df.head())

=======================================================
 FINAL ETL SUMMARY REPORT
=======================================================
Total Rows : 30
Total Columns : 9

Column Names:

['order_id', 'customer_name', 'product', 'category', 'quantity', 'unit_price', 'order_date', 'city', 'sales_rep']

Data Types:

order_id           int64
customer_name     object
product           object
category          object
quantity         float64
unit_price         int64
order_date        object
city              object
sales_rep         object
dtype: object

First 5 Rows of Cleaned Dataset:

   order_id customer_name   product     category  quantity  unit_price  \
0      1001  Ramesh Kumar    Laptop  ELECTRONICS       2.0       45000
1      1002    Priya Nair    Laptop  ELECTRONICS       1.0       15000
2      1003    AMIT VERMA  Keyboard  ACCESSORIES       3.0        1200
3      1004  Sunita Patel   Monitor  ELECTRONICS       2.0       22000
4      1005  Ramesh Kumar    Laptop  ELECTRONICS       2.0       45000

   order_date       city    sales_rep
0  2024-01-05     Mumbai  Anil Sharma
1  2024-01-07      Delhi   Sunita Rao
2  2024-01-08  Bangalore  Anil Sharma
3  2024-01-10    Chennai   Ravi Kumar
4  2024-01-05     Mumbai  Anil Sharma

In [17]:
# ==========================================================
# CELL 11 — Confirmation Message
# ==========================================================

print("ETL Process Completed Successfully!")

print("Cleaned dataset saved as cleaned_sales_data.csv")

ETL Process Completed Successfully!
Cleaned dataset saved as cleaned_sales_data.csv

In [18]:
# ==========================================================
# EXTRA — Dataset Overview
# ==========================================================

print("Number of Rows:", clean_df.shape[0])

print("Number of Columns:", clean_df.shape[1])

print("\nColumn Names:\n")

print(clean_df.columns.tolist())

Number of Rows: 30
Number of Columns: 9

Column Names:

['order_id', 'customer_name', 'product', 'category', 'quantity', 'unit_price', 'order_date', 'city', 'sales_rep']

In [24]:
# ==========================================================
# CHECK DUPLICATE ROWS
# ==========================================================

print(f"Before duplicate removal: {len(clean_df)} rows")

print(f"Duplicate rows: {clean_df.duplicated().sum()}")

# Show duplicate rows

print("\nDuplicate Rows:")

print(
    clean_df[
        clean_df.duplicated(
            subset=['order_id', 'customer_name'],
            keep=False
        )
    ]
)

# keep=False marks ALL duplicate rows

# ==========================================================
# CHECK DATE FORMAT
# ==========================================================

print("\nSample dates before parsing:")

print(clean_df['order_date'].head(8).tolist())

# ==========================================================
# CONVERT TO DATETIME
# ==========================================================

clean_df['order_date'] = pd.to_datetime(
    clean_df['order_date'],
    errors='coerce'
)

print("\nDates converted successfully!")

print(clean_df['order_date'].head())

Before duplicate removal: 30 rows
Duplicate rows: 0

Duplicate Rows:
Empty DataFrame
Columns: [order_id, customer_name, product, category, quantity, unit_price, order_date, city, sales_rep]
Index: []

Sample dates before parsing:
[Timestamp('2024-01-05 00:00:00'), Timestamp('2024-01-07 00:00:00'), Timestamp('2024-01-08 00:00:00'), Timestamp('2024-01-10 00:00:00'), Timestamp('2024-01-05 00:00:00'), NaT, Timestamp('2024-01-12 00:00:00'), Timestamp('2024-01-13 00:00:00')]

Dates converted successfully!
0   2024-01-05
1   2024-01-07
2   2024-01-08
3   2024-01-10
4   2024-01-05
Name: order_date, dtype: datetime64[ns]

In [25]:
# ==========================================================
# STANDARDIZE CUSTOMER NAMES
# ==========================================================

print("Customer names before cleaning:\n")

print(clean_df['customer_name'].unique()[:10])

# Convert names to proper title case
# Remove extra spaces

clean_df['customer_name'] = (
    clean_df['customer_name']
    .str.strip()
    .str.title()
)

print("\nCustomer names after cleaning:\n")

print(clean_df['customer_name'].unique()[:10])

Customer names before cleaning:

['Ramesh Kumar' 'Priya Nair' 'AMIT VERMA' 'Sunita Patel' 'kiran mehta'
 'Deepak Singh' nan 'Ananya Das' 'Vikram Iyer' 'Pooja Gupta']

Customer names after cleaning:

['Ramesh Kumar' 'Priya Nair' 'Amit Verma' 'Sunita Patel' 'Kiran Mehta'
 'Deepak Singh' nan 'Ananya Das' 'Vikram Iyer' 'Pooja Gupta']

In [4]:
#api key =e3671843bfecc36b02c35e351a5815ea
BASE_URL='https://api.openweathermap.org/data/2.5/weather'

CITIES=['Mumbai','Delhi','Bangalore','Chennai','Hyderabad',
                         'Kolkata','Pune','Jaipur']
print("API configured for ", len(CITIES), "cities")
print("Cities:",CITIES)

API configured for  8 cities
Cities: ['Mumbai', 'Delhi', 'Bangalore', 'Chennai', 'Hyderabad', 'Kolkata', 'Pune', 'Jaipur']