In [1]:
import sqlite3
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [4]:
print(f"pandas version:{pd.__version__}")
print(f"sqlite3 version:{sqlite3.version}")

pandas version:2.2.2
sqlite3 version:2.6.0

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
df=pd.read_csv('student_performance.csv')

In [7]:
print(f"Dataset loaded: {df.shape[0]} students, {df.shape[1]} columns")
print(f"Columns: {df.columns.tolist()}")
print("\nFirst 3 rows:")
print(df.head(3))

Dataset loaded: 30 students, 13 columns
Columns: ['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

First 3 rows:
   student_id          name  age  gender        department  semester  \
0        1001  Aarav Sharma   19    Male  Computer Science         2
1        1002   Priya Patel   20  Female  Computer Science         2
2        1003   Rohit Verma   19    Male       Electronics         2

   math_score  science_score  english_score  programming_score  \
0          85             78             72                 91
1          76             82             88                 79
2          65             74             61                 55

   attendance_percentage       city  admission_year
0                     92     Mumbai            2023
1                     87  Ahmedabad            2023
2                     78      Delhi            2023

In [8]:
print(f"dataset size : {len(df)}")

dataset size : 30

In [9]:
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [10]:
conn=sqlite3.connect('college.db')
#conn=our connection to the database
#college.db=the file will be created in colab's filesystem
#if college.db aldready exits it will create new file with same name
cursor=conn.cursor()

In [11]:
cursor = conn.cursor()
df.to_sql('students',conn,if_exists='replace',index=False)
cursor.execute("SELECT COUNT(*) FROM students")
count=cursor.fetchone()[0]
print("Number of rows inserted into 'students' table",count)

Number of rows inserted into 'students' table 30

In [14]:
cursor.execute("pragma table_info(students)")
columns_info=cursor.fetchall()
#fetchall retrieve all results rows(not just one)
print("table structure of students: ")
print(f"{'column name':<25}{'data type':<12}")
print("-"*45)
for col in columns_info:
  print(f"{col[1]:<25}{col[2]:<12}")

table structure of students:
column name              data type
---------------------------------------------
student_id               INTEGER
name                     TEXT
age                      INTEGER
gender                   TEXT
department               TEXT
semester                 INTEGER
math_score               INTEGER
science_score            INTEGER
english_score            INTEGER
programming_score        INTEGER
attendance_percentage    INTEGER
city                     TEXT
admission_year           INTEGER

In [15]:
def run_query(sql, description=""):
    """Runs a SQL query and returns results as a pandas dataframe

    Parameters:
    ----------------
    sql : str
        SQL query string
    description : str
        Label to print above the results

    Returns:
    ----------------
    Pandas DataFrame containing the query results
    """

    if description:
        print(f"\n{'='*55}")
        print(description)
        print(f"{'='*55}")

    result = pd.read_sql_query(sql, conn)
    print(result.to_string(index=False))

    return result


print("Helper function 'run_query' defined successfully")
print("Usage: run_query(sql_string, description)")

Helper function 'run_query' defined successfully
Usage: run_query(sql_string, description)

In [16]:
run_query(
    "SELECT * FROM students",
    "All Students"
)

=======================================================
All Students
=======================================================
 student_id           name  age gender       department  semester  math_score  science_score  english_score  programming_score  attendance_percentage               city  admission_year
       1001   Aarav Sharma   19   Male Computer Science         2          85             78             72                 91                     92             Mumbai            2023
       1002    Priya Patel   20 Female Computer Science         2          76             82             88                 79                     87          Ahmedabad            2023
       1003    Rohit Verma   19   Male      Electronics         2          65             74             61                 55                     78              Delhi            2023
       1004    Sneha Reddy   20 Female       Mechanical         2          70             80             75                 48                     95          Hyderabad            2023
       1005     Arjun Nair   19   Male Computer Science         2          92             88             81                 95                     90              Kochi            2023
       1006    Meera Joshi   20 Female      Electronics         2          58             66             70                 52                     72               Pune            2023
       1007    Kiran Kumar   21   Male            Civil         2          73             69             65                 40                     85          Bangalore            2023
       1008    Divya Singh   19 Female Computer Science         2          88             91             84                 93                     96            Lucknow            2023
       1009   Rahul Mishra   20   Male       Mechanical         2          62             71             58                 45                     68           Varanasi            2023
       1010     Ananya Das   19 Female Computer Science         2          95             89             90                 97                     98            Kolkata            2023
       1011    Vikram Iyer   20   Male      Electronics         2          80             75             68                 72                     83            Chennai            2023
       1012    Pooja Gupta   19 Female            Civil         2          67             72             79                 44                     80             Jaipur            2023
       1013     Suresh Rao   21   Male Computer Science         2          83             86             77                 88                     88             Mysore            2023
       1014  Kavya Nambiar   20 Female       Mechanical         2          74             78             82                 51                     91           Thrissur            2023
       1015    Ajay Tiwari   19   Male Computer Science         2          71             69             64                 76                     75             Bhopal            2023
       1016   Ritu Agarwal   20 Female      Electronics         2          87             83             86                 69                     93               Agra            2023
       1017   Manoj Pandey   21   Male            Civil         2          56             61             55                 38                     65              Patna            2023
       1018 Swati Kulkarni   19 Female Computer Science         2          90             87             85                 92                     94             Nagpur            2023
       1019 Deepak Chauhan   20   Male       Mechanical         2          68             73             62                 49                     77           Dehradun            2023
       1020   Nisha Kapoor   19 Female Computer Science         2          79             84             81                 83                     89         Chandigarh            2023
       1021  Harish Pillai   20   Male      Electronics         2          64             70             67                 58                     74 Thiruvananthapuram            2023
       1022    Tanvi Mehta   19 Female Computer Science         2          93             90             88                 96                     97              Surat            2023
       1023   Sanjay Dubey   21   Male            Civil         2          61             66             59                 42                     70          Allahabad            2023
       1024  Preeti Saxena   20 Female       Mechanical         2          77             81             76                 53                     86             Kanpur            2023
       1025      Amit Bose   19   Male Computer Science         2          86             82             79                 89                     91            Kolkata            2023
       1026     Rekha Nair   20 Female      Electronics         2          72             77             73                 63                     82              Kochi            2023
       1027  Gaurav Shukla   21   Male Computer Science         2          84             79             75                 87                     87            Lucknow            2023
       1028  Sunita Pillai   19 Female            Civil         2          60             65             68                 39                     73 Thiruvananthapuram            2023
       1029     Nitin Jain   20   Male       Mechanical         2          75             76             70                 50                     84             Indore            2023
       1030 Akanksha Yadav   19 Female Computer Science         2          91             93             87                 94                     95               Agra            2023

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023
5,1006,Meera Joshi,20,Female,Electronics,2,58,66,70,52,72,Pune,2023
6,1007,Kiran Kumar,21,Male,Civil,2,73,69,65,40,85,Bangalore,2023
7,1008,Divya Singh,19,Female,Computer Science,2,88,91,84,93,96,Lucknow,2023
8,1009,Rahul Mishra,20,Male,Mechanical,2,62,71,58,45,68,Varanasi,2023
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023
10,1011,Vikram Iyer,20,Male,Electronics,2,80,75,68,72,83,Chennai,2023
11,1012,Pooja Gupta,19,Female,Civil,2,67,72,79,44,80,Jaipur,2023
12,1013,Suresh Rao,21,Male,Computer Science,2,83,86,77,88,88,Mysore,2023
13,1014,Kavya Nambiar,20,Female,Mechanical,2,74,78,82,51,91,Thrissur,2023
14,1015,Ajay Tiwari,19,Male,Computer Science,2,71,69,64,76,75,Bhopal,2023
15,1016,Ritu Agarwal,20,Female,Electronics,2,87,83,86,69,93,Agra,2023
16,1017,Manoj Pandey,21,Male,Civil,2,56,61,55,38,65,Patna,2023
17,1018,Swati Kulkarni,19,Female,Computer Science,2,90,87,85,92,94,Nagpur,2023
18,1019,Deepak Chauhan,20,Male,Mechanical,2,68,73,62,49,77,Dehradun,2023
19,1020,Nisha Kapoor,19,Female,Computer Science,2,79,84,81,83,89,Chandigarh,2023
20,1021,Harish Pillai,20,Male,Electronics,2,64,70,67,58,74,Thiruvananthapuram,2023
21,1022,Tanvi Mehta,19,Female,Computer Science,2,93,90,88,96,97,Surat,2023
22,1023,Sanjay Dubey,21,Male,Civil,2,61,66,59,42,70,Allahabad,2023
23,1024,Preeti Saxena,20,Female,Mechanical,2,77,81,76,53,86,Kanpur,2023
24,1025,Amit Bose,19,Male,Computer Science,2,86,82,79,89,91,Kolkata,2023
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023